#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a albert state=floating focus=on
bspc rule -a "*:google-chrome" desktop='^2' follow=on
bspc rule -a "*:slack" desktop='^3' follow=on
bspc rule -a "*:telegram" desktop='^3' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

compton -b
redshift-gtk &
nm-applet &
blueman-applet &
albert &
polybar top &
feh --bg-scale ~/Pictures/texture-wallpaper-10.jpg
gnome-terminal &
google-chrome &
slack &
/opt/telegram/Telegram -- %u &
