#! /bin/bash
#Variables

export LAP=eDP1
LAP_ID=$(bspc query -M -m $LAP)
SCREEN=$LAP

if [[ $(bspc query -M | wc -l) == 1 ]]; then
  bspc monitor -d I II III IV V VI VII VIII IX X
else
  MON=$(xrandr -q | grep -w connected | grep -v $LAP | cut -d" " -f1)

  bspc monitor "$LAP" -d I II III IV V
  bspc monitor "$MON" -d VI VII VIII IX X

  SCREEN=$MON
fi

bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config remove_unplugged_monitors   true
bspc config remove_disabled_monitors  true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a albert state=floating focus=on
bspc rule -a "*:google-chrome" desktop='^2' follow=on
bspc rule -a "*:slack" desktop='^3' follow=on
bspc rule -a "*:telegram" desktop='^3' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

MONITOR=$LAP polybar top &

# ------------------------------------
# Currently I use only one polybar
# with pin-workspace = false
# ------------------------------------
# if [[ $MON ]]; then
#   MONITOR=$MON polybar top &
# fi

bspc_events &

compton -b
redshift-gtk &
nm-applet &
blueman-applet &
albert &
gnome-terminal &
google-chrome &
slack &
/opt/telegram/Telegram -- %u &

sxhkd &
bash ~/.fehbg
